const data = [
    {
        "carname": "Toyota Vios",
        "status": "New",
        "image": "https://thvnext.bing.com/th/id/OIP.Yr2S1J2QiliLDNOAfhFm4QHaEB?w=338&h=184&c=7&r=0&o=7&cb=ucfimg2&pid=1.7&rm=3&ucfimg=1",
        "price": 500000000,
        "description": "A reliable and fuel-efficient sedan, perfect for city driving.",
        "mileage": "0",
        "yearofsell": "2018",
        "usage": "None",
        "color": "White",
        "transmission": "Automatic",
        "engine": "1.5L I4",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Honda Civic",
        "status": "New",
        "image": "https://img1.oto.com.vn/2022/08/29/AJxaR32b/honda-civic-781b.jpg",
        "price": 700000000,
        "description": "Sporty design with advanced technology and comfort.",
        "mileage": "0",
        "yearofsell": "2022",
        "usage": "None",
        "color": "Red",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Mazda 3",
        "status": "New",
        "image": "https://thvnext.bing.com/th/id/OIP.q9Ttqvjf5nnKV9JznPEpHAHaEL?w=310&h=180&c=7&r=0&o=7&cb=ucfimg2&pid=1.7&rm=3&ucfimg=1",
        "price": 750000000,
        "description": "Stylish sedan with premium features and smooth handling.",
        "mileage": "0",
        "yearofsell": "2023",
        "usage": "None",
        "color": "Blue",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Hyundai Elantra",
        "status": "New",
        "image": "https://thvnext.bing.com/th/id/OIP._Y0AjKMRhAnd8lBNL6-1rQHaEK?w=329&h=185&c=7&r=0&o=7&cb=ucfimg2&pid=1.7&rm=3&ucfimg=1",
        "price": 680000000,
        "description": "Modern design and efficient performance for daily commuting.",
        "mileage": "0",
        "yearofsell": "2023",
        "usage": "None",
        "color": "Silver",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Kia Seltos",
        "status": "New",
        "image": "https://thvnext.bing.com/th/id/OIP.x5ufSRLgHJl-8ovx8gx-yQHaEo?w=271&h=180&c=7&r=0&o=7&cb=ucfimg2&pid=1.7&rm=3&ucfimg=1",
        "price": 800000000,
        "description": "Compact SUV with spacious interior and advanced safety.",
        "mileage": "0",
        "yearofsell": "2023",
        "usage": "None",
        "color": "Black",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Ford Ranger",
        "status": "New",
        "image": "https://thvnext.bing.com/th/id/OIP.9iNEFJwVY8gjlcf433RDagHaEL?w=315&h=180&c=7&r=0&o=7&cb=ucfimg2&pid=1.7&rm=3&ucfimg=1",
        "price": 900000000,
        "description": "Durable pickup truck with powerful engine and versatility.",
        "mileage": "0",
        "yearofsell": "2023",
        "usage": "None",
        "color": "Gray",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "VinFast VF e34",
        "status": "New",
        "image": "https://thvnext.bing.com/th/id/OIP.lt3Lbh6iY7pC1cD6N_usOgHaFj?w=227&h=180&c=7&r=0&o=7&cb=ucfimg2&pid=1.7&rm=3&ucfimg=1",
        "price": 690000000,
        "description": "Vietnamese electric SUV with modern features and eco-friendly drive.",
        "mileage": "0",
        "yearofsell": "2023",
        "usage": "None",
        "color": "Green",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Mercedes-Benz C-Class",
        "status": "New",
        "image": "https://thvnext.bing.com/th/id/OIP.44jE2Ds_DQPb4hjuiGQS-wHaEK?w=302&h=180&c=7&r=0&o=7&cb=ucfimg2&pid=1.7&rm=3&ucfimg=1",
        "price": 1600000000,
        "description": "Luxury sedan with top-tier comfort and performance.",
        "mileage": "0",
        "yearofsell": "2023",
        "usage": "None",
        "color": "White",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "BMW 3 Series",
        "status": "New",
        "image": "https://thvnext.bing.com/th/id/OIP.je2ZzL2VKczVyagzp7Zt7AHaEK?w=333&h=187&c=7&r=0&o=7&cb=ucfimg2&pid=1.7&rm=3&ucfimg=1",
        "price": 1700000000,
        "description": "Dynamic driving experience with elegant design and technology.",
        "mileage": "0",
        "yearofsell": "2023",
        "usage": "None",
        "color": "Black",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Audi A4",
        "status": "New",
        "image": "https://thvnext.bing.com/th/id/OIP.TwDDCU5JJkIl9uJkCX_45AHaEK?w=331&h=186&c=7&r=0&o=7&cb=ucfimg2&pid=1.7&rm=3&ucfimg=1",
        "price": 1650000000,
        "description": "Premium sedan with refined interior and advanced safety features.",
        "mileage": "0",
        "yearofsell": "2023",
        "usage": "None",
        "color": "Blue",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Lexus ES",
        "status": "Old",
        "image": "https://danchoioto.vn/wp-content/uploads/2020/12/lexus-es-la-mau-xe-thuoc-phan-khuc-sedan-hang-sang-co-trung.jpg.webp",
        "price": 1200000000,
        "description": "Luxury sedan with smooth ride and high-end amenities.",
        "mileage": "15000",
        "yearofsell": "2020",
        "usage": "Daily commute",
        "color": "Black",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Ford Crown Victoria Police Interceptor",
        "status": "Old",
        "image": "https://s3-screenshots.int-cdn.lcpdfrusercontent.com/monthly_2022_12/1.jpg.c677973797cc34ece5fcb36d60a19c24.jpg",
        "price": 350000000,
        "description": "Classic American police car, reliable and tough.",
        "mileage": "120000",
        "yearofsell": "2011",
        "usage": "Law enforcement",
        "color": "White/Blue",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Ford Explorer Police Utility",
        "status": "Old",
        "image": "https://s3-screenshots.int-cdn.lcpdfrusercontent.com/monthly_2025_09/GrandTheftAutoVScreenshot2025_09.07-19.22_09_38.png.fdfbffd59d0c0f1b555edc5ffe7bac3c.png",
        "price": 600000000,
        "description": "Modern police SUV, used by departments nationwide.",
        "mileage": "90000",
        "yearofsell": "2017",
        "usage": "Law enforcement",
        "color": "Black",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Mercedes-Benz Sprinter Van",
        "status": "Old",
        "image": "https://tse1.mm.bing.net/th/id/OIP.MwxYCfrNKkAAAOBMnrTbmAHaFj?cb=ucfimg2ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3",
        "price": 800000000,
        "description": "Spacious van, ideal for delivery and service businesses.",
        "mileage": "85000",
        "yearofsell": "2018",
        "usage": "Service",
        "color": "White",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Isuzu N-Series Truck",
        "status": "Old",
        "image": "https://tse2.mm.bing.net/th/id/OIP.FtYyyB52khAF57TQkTWQ1gHaDl?cb=ucfimg2ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3",
        "price": 700000000,
        "description": "Reliable light-duty truck for various service needs.",
        "mileage": "110000",
        "yearofsell": "2016",
        "usage": "Service",
        "color": "Silver",
        "transmission": "Manual",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Hyundai Accent",
        "status": "Old",
        "image": "https://tse3.mm.bing.net/th/id/OIP.5WaFxu95Gpac2-fIlAabTQHaE6?cb=ucfimg2ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3",
        "price": 400000000,
        "description": "Economical sedan, perfect for daily commuting.",
        "mileage": "65000",
        "yearofsell": "2019",
        "usage": "Daily commute",
        "color": "Gray",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Toyota Camry",
        "status": "Old",
        "image": "https://th.bing.com/th/id/R.64ff3adee5d322408c5d4c7285d5d3b7?rik=bKYhjY%2btYcKJcw&pid=ImgRaw&r=0",
        "price": 600000000,
        "description": "Comfortable and reliable sedan for everyday use.",
        "mileage": "90000",
        "yearofsell": "2017",
        "usage": "Daily commute",
        "color": "Black",
        "transmission": "Automatic",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Porsche 911 GT3",
        "status": "Old",
        "image": "https://uncrate.com/p/2023/10/porsche-911-gt3-r-rennsport-1.jpg",
        "price": 7000000000,
        "description": "High-performance sports car, track ready.",
        "mileage": "18000",
        "yearofsell": "2019",
        "usage": "Motorsport",
        "color": "Blue",
        "transmission": "Manual",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Honda Civic Type R",
        "status": "Old",
        "image": "https://tse3.mm.bing.net/th/id/OIP.8uZgXZupryt5N86vPy8WMwHaEK?cb=ucfimg2ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3",
        "price": 1200000000,
        "description": "Hot hatch with motorsport pedigree, fun to drive.",
        "mileage": "25000",
        "yearofsell": "2020",
        "usage": "Motorsport",
        "color": "White",
        "transmission": "Manual",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Chevrolet Corvette C1",
        "status": "Old",
        "image": "https://erclassics.b-cdn.net/media/catalog/product/cache/2/thumbnail/1920x/17f82f742ffe127f42dca9de82fb58b1/c/h/chevrolet-corvette-c1-1961-c5356-054.jpg",
        "price": 3500000000,
        "description": "Classic American sports car, mostly used for display at exhibitions.",
        "mileage": "5000",
        "yearofsell": "1959",
        "usage": "Display",
        "color": "White/Red",
        "transmission": "Manual",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    },
    {
        "carname": "Lamborghini Miura",
        "status": "Old",
        "image": "https://assets.dyler.com/uploads/posts/52/images/661/lamborghini-miura.jpg",
        "price": 15000000000,
        "description": "Legendary supercar, rarely driven, mostly for display.",
        "mileage": "3000",
        "yearofsell": "1971",
        "usage": "Display",
        "color": "Yellow",
        "transmission": "Manual",
        "engine": "",
        "contact": "0399220978",
        "plate": "",
        "confirmonsale": true
    }
];